name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Runs the test suite against all supported branches and combinations.
  # Linting is performed on all jobs run against PHPCS `dev-master`.
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '8.0', '8.1', '8.2', '8.3' ]
        phpcs_version: [ 'lowest', 'dev-master' ]
        extensions: [ '' ]
        coverage: [false]

        include:
          - php: '7.4'
            phpcs_version: 'dev-master'
            extensions: ':mbstring' # = Disable Mbstring.
            coverage: true # Make sure coverage is recorded for this too.

          # Run code coverage builds against high/low PHP and high/low PHPCS.
          # Note: Until PHPCS supports PHPUnit 9, we cannot run code coverage on PHP 8.0+.
          - php: '5.4'
            phpcs_version: 'dev-master'
            extensions: ''
            coverage: true
          - php: '5.4'
            phpcs_version: 'lowest'
            extensions: ''
            coverage: true
          - php: '7.4'
            phpcs_version: 'dev-master'
            extensions: ''
            coverage: true
          - php: '7.4'
            phpcs_version: 'lowest'
            extensions: ''
            coverage: true

          # Add extra build to test against PHPCS 4.
          #- php: '7.4'
          #  phpcs_version: '4.0.x-dev as 3.9.99'

    name: PHP ${{ matrix.php }} on PHPCS ${{ matrix.phpcs_version }}

    continue-on-error: ${{ matrix.php == '8.3' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # On stable PHPCS versions, allow for PHP deprecation notices.
      # Unit tests don't need to fail on those for stable releases where those issues won't get fixed anymore.
      - name: Setup ini config
        id: set_ini
        run: |
          if [ "${{ matrix.phpcs_version }}" != "dev-master" ]; then
            echo 'PHP_INI=error_reporting=E_ALL & ~E_DEPRECATED, display_errors=On' >> $GITHUB_OUTPUT
          else
            echo 'PHP_INI=error_reporting=-1, display_errors=On' >> $GITHUB_OUTPUT
          fi

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: ${{ steps.set_ini.outputs.PHP_INI }}
          coverage: ${{ matrix.coverage && 'xdebug' || 'none' }}
          tools: cs2pr

      - name: "Set PHPCS version (master)"
        if: ${{ matrix.phpcs_version != 'lowest' }}
        run: composer require squizlabs/php_codesniffer:"${{ matrix.phpcs_version }}" --no-update --no-scripts --no-interaction

      - name: Install Composer dependencies (PHP < 8.0 )
        if: ${{ matrix.php < 8.0 }}
        uses: ramsey/composer-install@v2
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Install Composer dependencies (PHP >= 8.0)
        if: ${{ matrix.php >= 8.0 }}
        uses: ramsey/composer-install@v2
        with:
          composer-options: --ignore-platform-req=php+
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: "Set PHPCS version (lowest)"
        if: ${{ matrix.phpcs_version == 'lowest' }}
        run: composer update squizlabs/php_codesniffer --prefer-lowest --ignore-platform-req=php+ --no-scripts --no-interaction

      - name: Lint PHP files against parse errors
        if: ${{ matrix.phpcs_version == 'dev-master' }}
        run: composer lint -- --checkstyle | cs2pr

      - name: Run the unit tests without code coverage - PHP 5.4 - 8.0
        if: ${{ matrix.php < '8.1' && matrix.coverage == false }}
        run: composer run-tests

      - name: Run the unit tests with code coverage - PHP 5.4 - 8.0
        if: ${{ matrix.php < '8.1' && matrix.coverage == true  }}
        run: composer coverage

      # Until PHPCS supports PHPUnit 9, we cannot run code coverage on PHP 8.0+.
      - name: Run the unit tests without code coverage - PHP >= 8.1
        if: ${{ matrix.php >= '8.1' && matrix.coverage == false  }}
        run: composer run-tests -- --no-configuration --bootstrap=./Tests/bootstrap.php --dont-report-useless-tests

      - name: Send coverage report to Codecov
        if: ${{ success() && matrix.coverage == true }}
        uses: codecov/codecov-action@v3
        with:
          files: ./build/logs/clover.xml
          fail_ci_if_error: true
          verbose: true
